name: Feature Request
description: 새로운 기능을 제안합니다.
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      value: |
        ## 배경


        ## 목표


        ## 요구사항

    validations:
      required: true
